# Generated by Django 3.0.3 on 2020-03-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCBapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='memberId',
            new_name='member',
        ),
    ]
