# Generated by Django 3.0.3 on 2020-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCBapp', '0002_auto_20200326_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='commentId',
            field=models.ManyToManyField(null=True, to='FamilyCBapp.Comment', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredientId',
            field=models.ManyToManyField(null=True, to='FamilyCBapp.Ingredient', verbose_name='ingredients'),
        ),
    ]
