# Generated by Django 3.0.3 on 2020-03-26 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCBapp', '0003_auto_20200326_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='commentId',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientId',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
