# Generated by Django 3.0.3 on 2020-03-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyCBapp', '0004_auto_20200326_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='member',
            new_name='memberId',
        ),
    ]
