# Generated by Django 3.0.3 on 2020-03-13 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('privacy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('measurement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('familyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FamilyCBProject.Family', verbose_name='Families')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instruction', models.CharField(max_length=1000)),
                ('servings', models.IntegerField()),
                ('commentId', models.ManyToManyField(to='FamilyCBProject.Comment', verbose_name='Comments')),
                ('ingredientId', models.ManyToManyField(to='FamilyCBProject.Ingredient', verbose_name='ingredients')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FamilyCBProject.Member')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='FamilyCBProject.Member'),
        ),
        migrations.AddField(
            model_name='family',
            name='memberId',
            field=models.ManyToManyField(to='FamilyCBProject.Member', verbose_name='Members'),
        ),
        migrations.AddField(
            model_name='family',
            name='recipeId',
            field=models.ManyToManyField(to='FamilyCBProject.Recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='memberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FamilyCBProject.Member', verbose_name='Members'),
        ),
    ]
